export { castDataPropToBoolean } from "./castDataPropToBoolean/index.js"
export { castNodeToBoolean } from "./castNodeToBoolean/index.js"
export { extractProps } from "./extractProps/index.js"
export { mergeRefs } from "./mergeRefs/index.js"
export type { PossibleRef } from "./mergeRefs/index.js"
